# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-17 11:23
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import filebrowser.fields
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('portal', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Configuration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publications_page_size', models.IntegerField(default=6, verbose_name='News Page Size')),
            ],
        ),
        migrations.CreateModel(
            name='PortalRegion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region_name', models.CharField(max_length=64, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='PortalRegionContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', tinymce.models.HTMLField(blank=True, null=True)),
                ('latest_from', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='latest_from_regions', to='portal.MenuItem')),
                ('one_from', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='one_from_regions', to='portal.MenuItem')),
            ],
            options={
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[(b'I', 'Hidden'), (b'P', 'Published'), (b'H', 'Holded'), (b'N', 'Draft')], default=b'N', max_length=5)),
                ('publication_date', models.DateField(db_index=True)),
                ('show_date', models.BooleanField(default=False)),
                ('slug', models.CharField(blank=True, max_length=100, null=True, unique_for_date=b'publication_date')),
                ('type', models.CharField(choices=[(b'Note', 'Publication'), (b'Photo', 'Photogallery'), (b'Rss', 'Rss')], default=b'Note', max_length=20)),
                ('title', models.CharField(blank=True, max_length=256, null=True)),
                ('short_text', tinymce.models.HTMLField()),
                ('text', tinymce.models.HTMLField(blank=True, null=True)),
                ('rss_url', models.CharField(blank=True, max_length=512, null=True)),
                ('old_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('locale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.Lang')),
            ],
            options={
                'ordering': ('-publication_date',),
            },
        ),
        migrations.CreateModel(
            name='PublicationImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', filebrowser.fields.FileBrowseField(max_length=255)),
                ('caption', models.CharField(blank=True, max_length=255, null=True)),
                ('name', models.CharField(blank=True, max_length=128, null=True)),
                ('publication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='publications.Publication')),
            ],
            options={
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='PublicationSubcategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='publications.Publication')),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.MenuItem')),
            ],
        ),
        migrations.CreateModel(
            name='RssImportStream',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=True)),
                ('rss_url', models.CharField(max_length=256)),
                ('pool_period_mins', models.IntegerField(default=30)),
                ('next_pool', models.DateTimeField()),
                ('link_caption', models.CharField(max_length=255)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.Lang')),
                ('menu_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.MenuItem')),
            ],
        ),
        migrations.AddField(
            model_name='publication',
            name='rss_stream',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='publications.RssImportStream'),
        ),
        migrations.AddField(
            model_name='publication',
            name='subcategory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.MenuItem'),
        ),
        migrations.AddField(
            model_name='portalregioncontent',
            name='publication',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='publications.Publication'),
        ),
        migrations.AddField(
            model_name='portalregioncontent',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='publications.PortalRegion'),
        ),
        migrations.AddField(
            model_name='configuration',
            name='last_old_publication',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='publications.Publication'),
        ),
        migrations.AlterUniqueTogether(
            name='publicationimage',
            unique_together=set([('publication', 'file')]),
        ),
        migrations.AlterUniqueTogether(
            name='publication',
            unique_together=set([('publication_date', 'slug'), ('rss_stream', 'rss_url')]),
        ),
        migrations.AlterIndexTogether(
            name='publication',
            index_together=set([('state', 'publication_date'), ('state', 'subcategory', 'publication_date')]),
        ),
    ]
