# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-18 20:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='portalregioncontent',
            options={'ordering': ('region__region_name', 'order', 'id')},
        ),
        migrations.AddField(
            model_name='portalregioncontent',
            name='order',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='portalregioncontent',
            name='title',
            field=models.TextField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='portalregioncontent',
            name='url',
            field=models.TextField(blank=True, max_length=256, null=True),
        ),
    ]
