version: "2"

services:
  mysql:
    image: mysql:5.7
    environment:
      TZ: UTC
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      TERM: xterm
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "23306:3306"

volumes:
  mysql_data:
