# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-17 11:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lang',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=2)),
                ('caption', models.CharField(max_length=50)),
                ('default', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ('-default', 'caption'),
            },
        ),
        migrations.CreateModel(
            name='LangLocale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(max_length=50)),
                ('lang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.Lang')),
                ('locale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lang_translated', to='portal.Lang')),
            ],
        ),
        migrations.CreateModel(
            name='MainMenu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(max_length=100, unique=True)),
                ('order', models.SmallIntegerField(default=0)),
                ('hidden', models.BooleanField(default=False)),
                ('width', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'ordering': ('hidden', 'order', 'caption'),
            },
        ),
        migrations.CreateModel(
            name='MainMenuI18n',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(max_length=100)),
                ('locale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.Lang')),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.MainMenu')),
            ],
            options={
                'ordering': ('menu__order', 'locale__code'),
            },
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(max_length=100)),
                ('order', models.SmallIntegerField(default=0)),
                ('slug', models.SlugField(blank=True, max_length=32, null=True)),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.MainMenu')),
            ],
            options={
                'ordering': ('menu__hidden', 'menu__order', 'order', 'caption'),
            },
        ),
        migrations.CreateModel(
            name='MenuItemI18n',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(max_length=100)),
                ('locale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.Lang')),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.MainMenu')),
                ('menu_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.MenuItem')),
            ],
            options={
                'ordering': ('menu__order', 'locale__code'),
            },
        ),
        migrations.AlterUniqueTogether(
            name='menuitemi18n',
            unique_together=set([('menu', 'caption', 'locale'), ('menu_item', 'locale')]),
        ),
        migrations.AlterUniqueTogether(
            name='menuitem',
            unique_together=set([('menu', 'caption')]),
        ),
        migrations.AlterUniqueTogether(
            name='mainmenui18n',
            unique_together=set([('menu', 'locale'), ('menu', 'caption')]),
        ),
        migrations.AlterUniqueTogether(
            name='langlocale',
            unique_together=set([('lang', 'locale')]),
        ),
    ]
