# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-09 21:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0005_auto_20150615_2100'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='menuitem',
            unique_together=set([('menu', 'caption')]),
        ),
        migrations.RemoveField(
            model_name='mainmenu',
            name='locale',
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='locale',
        ),
    ]
