# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-15 20:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0006_auto_20160410_0046'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='slug',
            field=models.SlugField(blank=True, max_length=32, null=True),
        ),
    ]
